services:
  - type: web
    name: anime-multporn-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python merged_bot.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
